<?php
//This class was generated by PHPDBParser(Java) at 2015/05/30 22:30:49
class menulist_item
{
	//Mysql connection
	private $db;
	//Execute result
	private $Result;
	//rows number of result
	private $Rows;

	//Database fields
	public $id;
	public $itemName;
	public $price;
	public $itemClass;

	public function __construct($db)
	{
		$this->db=$db;
	}

	public function Insert($id,$itemName,$price,$itemClass)
	{
		$sql = 'INSERT INTO `menulist_item` (`id`,`itemName`,`price`,`itemClass`) VALUES (\''.$id.'\',\''.$itemName.'\',\''.$price.'\',\''.$itemClass.'\');';
		$this->db->query($sql);
	}

	public function Update($id,$itemName,$price,$itemClass)
	{
		$sql = 'UPDATE `menulist_item` SET `id`=\''.$id.'\' ,`itemName`=\''.$itemName.'\' ,`price`=\''.$price.'\' ,`itemClass`=\''.$itemClass.'\' ;';
		$this->db->query($sql);
	}

	public function Select()
	{
		$this->Rows=0;
		$sql="SELECT * FROM `menulist_item";
		//store return data to $this->Result
		$this->Result=$this->db->query($sql);
		//count the numbers of return data and save to $this->Rows
		$this->Rows=$this->db->num_rows($this->Result);
	}

	public function Delete($itemName)
	{
		$sql="DELETE FROM `menulist_item` WHERE itemName='.$itemName.'";
		$this->db->query($sql);
	}

	public function HasNext()
	{
		if($this->Rows>0)
		{
			$temp=$this->db->fetch_array($this->Result);
			$this->id=$temp['id'];
			$this->itemName=$temp['itemName'];
			$this->price=$temp['price'];
			$this->itemClass=$temp['itemClass'];
			$this->Rows--;
			return true;
		}
		return false;
	}
	public function HasNextInClass($itemClass)
	{
		if($this->Rows>0)
		{
			$temp=$this->db->fetch_array($this->Result);
			$this->id=$temp['id'];
			$this->itemName=$temp['itemName'];
			$this->price=$temp['price'];
			$this->itemClass=$temp['itemClass'];
			$this->Rows--;
			if($this->itemClass==$itemClass)
			{
				return true;
			}
		}
		return false;
	}
}
?>
