<?php
//This class was generated by PHPDBParser(Java) at 2015/06/04 14:41:38
class shoppinglist
{
	//Mysql connection
	private $db;
	//Execute result
	private $Result;
	//rows number of result
	private $Rows;

	//Database fields
	public $id;
	public $name;
	public $depart;
	public $shopclass;
	public $shopname;
	public $deadline;

	public function __construct($db)
	{
		$this->db=$db;
	}

	public function Insert($name,$depart,$shopclass,$shopname,$deadline)
	{
		$sql = 'INSERT INTO `shoppinglist` (`name`,`depart`,`shopclass`,`shopname`,`deadline`) VALUES (\''.$name.'\',\''.$depart.'\',\''.$shopclass.'\',\''.$shopname.'\',\''.$deadline.'\');';
		$this->db->query($sql);
	}

	public function Update($name,$depart,$shopclass,$shopname,$deadline)
	{
		$sql = 'UPDATE `shoppinglist` SET `name`=\''.$name.'\' ,`depart`=\''.$depart.'\' ,`shopclass`=\''.$shopclass.'\' ,`shopname`=\''.$shopname.'\' ,`deadline`=\''.$deadline.'\' ;';
		$this->db->query($sql);
	}

	public function Select()
	{
		$this->Rows=0;
		$sql="SELECT * FROM `shoppinglist`";
		//store return data to $this->Result
		$this->Result=$this->db->query($sql);
		//count the numbers of return data and save to $this->Rows
		$this->Rows=$this->db->num_rows($this->Result);
	}

	public function Delete()
	{
		$sql="your sql command here";
		$this->db->query($sql);
	}

	public function HasNext()
	{
		if($this->Rows>0)
		{
			$temp=$this->db->fetch_array($this->Result);
			$this->id=$temp['id'];
			$this->name=$temp['name'];
			$this->depart=$temp['depart'];
			$this->shopclass=$temp['shopclass'];
			$this->shopname=$temp['shopname'];
			$this->deadline=$temp['deadline'];
			$this->Rows--;
			return true;
		}
		return false;
	}
}
?>