<?php
//This class was generated by PHPDBParser(Java) at 2015/06/02 22:24:03
class shoplist_class
{
	//Mysql connection
	private $db;
	//Execute result
	private $Result;
	//rows number of result
	private $Rows;

	//Database fields
	public $className;

	public function __construct($db)
	{
		$this->db=$db;
	}

	public function Insert($id,$className)
	{
		$sql = 'INSERT INTO `shoplist_class` (`id`,`className`) VALUES (\''.$className.'\');';
		$this->db->query($sql);
	}

	public function Update($id,$className)
	{
		$sql = 'UPDATE `shoplist_class` SET `className`=\''.$className.'\' ;';
		$this->db->query($sql);
	}

	public function Select()
	{
		$this->Rows=0;
		$sql="SELECT * FROM `shoplist_class`";
		//store return data to $this->Result
		$this->Result=$this->db->query($sql);
		//count the numbers of return data and save to $this->Rows
		$this->Rows=$this->db->num_rows($this->Result);
	}

	public function Delete()
	{
		$sql="your sql command here";
		$this->db->query($sql);
	}

	public function HasNext()
	{
		if($this->Rows>0)
		{
			$temp=$this->db->fetch_array($this->Result);
			$this->className=$temp['className'];
			$this->Rows--;
			return true;
		}
		return false;
	}
}
?>