<?php
//This class was generated by PHPDBParser(Java) at 2015/06/04 22:53:16
class shoplist_shopinfo
{
	//Mysql connection
	private $db;
	//Execute result
	private $Result;
	//rows number of result
	private $Rows;

	//Database fields
	public $id;
	public $shopclass;
	public $shopname;
	public $address;
	public $opentime;
	public $info;

	public function __construct($db)
	{
		$this->db=$db;
	}

	public function Insert($id,$shopclass,$shopname,$address,$opentime,$info)
	{
		$sql = 'INSERT INTO `shoplist_shopinfo` (`id`,`shopclass`,`shopname`,`address`,`opentime`,`info`) VALUES (\''.$id.'\',\''.$shopclass.'\',\''.$shopname.'\',\''.$address.'\',\''.$opentime.'\',\''.$info.'\');';
		$this->db->query($sql);
	}

	public function Update($id,$shopclass,$shopname,$address,$opentime,$info)
	{
		$sql = 'UPDATE `shoplist_shopinfo` SET `id`=\''.$id.'\' ,`shopclass`=\''.$shopclass.'\' ,`shopname`=\''.$shopname.'\' ,`address`=\''.$address.'\' ,`opentime`=\''.$opentime.'\' ,`info`=\''.$info.'\' ;';
		$this->db->query($sql);
	}

	public function Select()
	{
		$this->Rows=0;
		$sql="SELECT * FROM `shoplist_shopinfo`";
		//store return data to $this->Result
		$this->Result=$this->db->query($sql);
		//count the numbers of return data and save to $this->Rows
		$this->Rows=$this->db->num_rows($this->Result);
	}

	public function Delete()
	{
		$sql="your sql command here";
		$this->db->query($sql);
	}

	public function HasNext()
	{
		if($this->Rows>0)
		{
			$temp=$this->db->fetch_array($this->Result);
			$this->id=$temp['id'];
			$this->shopclass=$temp['shopclass'];
			$this->shopname=$temp['shopname'];
			$this->address=$temp['address'];
			$this->opentime=$temp['opentime'];
			$this->info=$temp['info'];
			$this->Rows--;
			return true;
		}
		return false;
	}
	public function SelectByID($id)
	{
		$this->Rows=0;
		$sql="SELECT * FROM `shoplist_shopinfo` where id='".$id."'";
		//store return data to $this->Result
		$this->Result=$this->db->query($sql);
		//count the numbers of return data and save to $this->Rows
		$this->Rows=$this->db->num_rows($this->Result);
		$temp=$this->db->fetch_array($this->Result);
			$this->id=$temp['id'];
			$this->shopclass=$temp['shopclass'];
			$this->shopname=$temp['shopname'];
			$this->address=$temp['address'];
			$this->opentime=$temp['opentime'];
			$this->info=$temp['info'];
		
	}
}
?>
