<?php
//This class was generated by PHPDBParser(Java) at 2015/07/22 20:07:33
class class_constraint
{
	//Mysql connection
	private $db;
	//Execute result
	private $Result;
	//rows number of result
	private $Rows;

	//Database fields
	public $pat_name;
	public $class1;
	public $class2;

	public function __construct($db)
	{
		$this->db=$db;
	}

	public function Insert($pat_name,$class1,$class2)
	{
		$sql = 'INSERT INTO `class_constraint` (`pat_name`,`class1`,`class2`) VALUES (\''.$pat_name.'\',\''.$class1.'\',\''.$class2.'\');';
		$this->db->query($sql);
	}

	public function Update($pat_name,$class1,$class2)
	{
		$sql = 'UPDATE `class_constraint` SET `pat_name`=\''.$pat_name.'\' ,`class1`=\''.$class1.'\' ,`class2`=\''.$class2.'\' ;';
		$this->db->query($sql);
	}

	public function Select()
	{
		$this->Rows=0;
		$sql="your sql command here";
		//store return data to $this->Result
		$this->Result=$this->db->query($sql);
		//count the numbers of return data and save to $this->Rows
		$this->Rows=$this->db->num_rows($this->Result);
	}

	public function Delete()
	{
		$sql="your sql command here";
		$this->db->query($sql);
	}

	public function HasNext()
	{
		if($this->Rows>0)
		{
			$temp=$this->db->fetch_array($this->Result);
			$this->pat_name=$temp['pat_name'];
			$this->class1=$temp['class1'];
			$this->class2=$temp['class2'];
			$this->Rows--;
			return true;
		}
		return false;
	}
}
?>
