<?php
//This class was generated by PHPDBParser(Java) at 2015/07/21 22:08:03
class content
{
	//Mysql connection
	private $db;
	//Execute result
	private $Result;
	//rows number of result
	private $Rows;

	//Database fields
	public $name;
	public $problem;
	public $solution;
	public $consequences;

	public function __construct($db)
	{
		$this->db=$db;
	}

	public function Insert($name,$problem,$solution,$consequences)
	{
		$sql = 'INSERT INTO `content` (`name`,`problem`,`solution`,`consequences`) VALUES (\''.$name.'\',\''.$problem.'\',\''.$solution.'\',\''.$consequences.'\');';
		$this->db->query($sql);
	}

	public function Update($name,$problem,$solution,$consequences)
	{
		$sql = 'UPDATE `content` SET `name`=\''.$name.'\' ,`problem`=\''.$problem.'\' ,`solution`=\''.$solution.'\' ,`consequences`=\''.$consequences.'\' ;';
		$this->db->query($sql);
	}

	public function Select($pat_name)
	{
		$this->Rows=0;
		$sql="select * from `content` where `name` LIKE '%".$pat_name."%'";
		//store return data to $this->Result
		$this->Result=$this->db->query($sql);
		//count the numbers of return data and save to $this->Rows
		$this->Rows=$this->db->num_rows($this->Result);
	}

	public function Delete()
	{
		$sql="your sql command here";
		$this->db->query($sql);
	}

	public function HasNext()
	{
		if($this->Rows>0)
		{
			$temp=$this->db->fetch_array($this->Result);
			$this->name=$temp['name'];
			$this->problem=$temp['problem'];
			$this->solution=$temp['solution'];
			$this->consequences=$temp['consequences'];
			$this->Rows--;
			return true;
		}
		return false;
	}
}
?>