<?
//This class was generated by PHPDBParser(Java) at 2015/07/22 20:10:36
class pat_usage
{
	//Mysql connection
	private $db;
	//Execute result
	private $Result;
	//rows number of result
	private $Rows;

	//Database fields
	public $req_id;
	public $pat_name;

	public function __construct($db)
	{
		$this->db=$db;
	}

	public function Insert($req_id,$pat_name)
	{
		$sql = 'INSERT INTO `pat_usage` (`req_id`,`pat_name`) VALUES (\''.$req_id.'\',\''.$pat_name.'\');';
		$this->db->query($sql);
	}

	public function Update($req_id,$pat_name)
	{
		$sql = 'UPDATE `pat_usage` SET `req_id`=\''.$req_id.'\' ,`pat_name`=\''.$pat_name.'\' ;';
		$this->db->query($sql);
	}

	public function Select()
	{
		$this->Rows=0;
		$sql="your sql command here";
		//store return data to $this->Result
		$this->Result=$this->db->query($sql);
		//count the numbers of return data and save to $this->Rows
		$this->Rows=$this->db->num_rows($this->Result);
	}

	public function Delete()
	{
		$sql="your sql command here";
		$this->db->query($sql);
	}

	public function HasNext()
	{
		if($this->Rows>0)
		{
			$temp=$this->db->fetch_array($this->Result);
			$this->req_id=$temp['req_id'];
			$this->pat_name=$temp['pat_name'];
			$this->Rows--;
			return true;
		}
		return false;
	}
}
?>
